create table orders
(
    order_id    uuid not null
        primary key,
    amount      numeric(38, 2),
    status      smallint,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    customer_id uuid,
    currency    varchar(255)
);

CREATE INDEX IF NOT EXISTS orders_by_created_at_idx ON orders (created_at);

create table line_items
(
    id           bigint generated by default as identity
        primary key,
    amount       numeric(38, 2),
    quantity     integer not null,
    order_id     uuid
        constraint fkcfmx8jqmqu18hhasfdf3w1m9u
            references orders,
    product_id   uuid,
    currency     varchar(255),
    sub_amount   numeric(38, 2),
    sub_currency varchar(255)
)