server:
  port: 9096
spring:
  application:
    name: product-bff-service
  threads:
    virtual:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application-name: ${spring.application.name}
  otlp:
    metrics:
      export:
        enabled: true
        step: 1m
        url: ${OTLP_BASE_URL:http://localhost:4318/v1/metrics}
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false

client:
  inventory:
    base-url: http://localhost:9095
  product:
    base-url: http://localhost:9094