server:
  port: 9093
  http2:
    enabled: true
spring:
  application:
    name: ordering-service
  threads:
    virtual:
      enabled: true
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: myuser
    password: secret
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application-name: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
        step: 1m
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false