@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Bob
participant Product
participant Order
queue OrderChangedEvent
participant Inventory
queue InventoryChangedEvent
participant Payment
participant Shipping



Bob -> Order
activate Order
Order --> OrderChangedEvent
Order --> Bob
deactivate Order


OrderChangedEvent  --> Inventory
activate Inventory
alt resevered
Inventory --> InventoryChangedEvent
else
Inventory --> InventoryChangedEvent
end
deactivate Inventory

@enduml